### ISSUE TITLE
[21w44a] Crashes on client startup

### ISSUE THREAD

**Issue by kwpugh** [MaximPixel/Just-Copper-Tools-Fabric#1]
Log:  https://paste.ee/p/pvkmP

Might be because of the changes in the latest Fabric API 42.1, not sure.

**Comment by kwpugh** [comment]
Might be because of line 10 here: 

![Screen Shot 2021-11-07 at 2 17 58 PM](https://user-images.githubusercontent.com/8809210/140660661-382e2a54-fc2e-45f5-8f74-739665157aa5.png)

**Comment by MaximPixel** [comment]
Thanks for finding the crash. Everything is now fixed and playable. The new version 1.1 will be approved soon.
