### ISSUE TITLE
Just Copper Tools breaks some workbench recipes.

### ISSUE THREAD

**Issue by Derpford** [MaximPixel/Just-Copper-Tools-Fabric#2]
Known affected recipes include the Oak Door and several recipes from TechReborn.

**Comment by Ayutac** [comment]
I believe the error is in the matcher of the repair recipe

**Comment by MaximPixel** [comment]
How do you know that this is the problem with this mod? Can you please send a screenshot, logs or something else so that I can try to solve the problem?

**Comment by MaximPixel** [comment]
My problem is due to one typo in the code. This issue has already been fixed.
